import type { DrsWorkflowPlan } from './drs.js'
import type {
  NormalizedMeshCiDockerBackendConfig,
  NormalizedMeshServiceConfig,
} from '../core/types.js'

export interface BackendDockerfileRenderInput {
  readonly service: NormalizedMeshServiceConfig
  readonly docker: {
    readonly nodeImage: string
    readonly backend: NormalizedMeshCiDockerBackendConfig
  }
  readonly drsPlan?: DrsWorkflowPlan
}

const GENERATED_HEADER = [
  '# Generated by @panomapp/mesh — do not edit.',
  '# Regenerate from monorepo root: npm run mesh:ci:generate',
  '# Prerequisite: vendored generated_modules must be built (CI "Prepare @panomapp/..." steps or npm run drs:build).',
].join('\n')

function resolveInstallCommand(plan: DrsWorkflowPlan | undefined, omitDev: boolean): string {
  const flag = omitDev ? ' --omit=dev' : ''
  if (!plan) {
    return `npm ci${flag}`
  }

  const command = plan.installCommand.trim()
  if (command.startsWith('npm install ') && command.includes('file:./generated_modules/')) {
    const fileArgs = command
      .slice('npm install '.length)
      .split(/\s+/)
      .filter(token => token.startsWith('file:'))
    if (fileArgs.length > 0) {
      return `npm ci${flag} \\\n  ${fileArgs.join(' \\\n  ')}`
    }
  }

  return `npm ci${flag}`
}

function aptInstallLines(packages: readonly string[]): string {
  if (packages.length === 0) return ''
  const list = packages.join(' ')
  return [
    'RUN apt-get update -o Acquire::Retries=3 -y \\',
    `  && apt-get install -y --no-install-recommends ${list} \\`,
    '  && rm -rf /var/lib/apt/lists/*',
    '',
  ].join('\n')
}

export function renderBackendDockerfile(input: BackendDockerfileRenderInput): string {
  const { service, docker, drsPlan } = input
  const { nodeImage, backend } = docker
  const exposePort = service.podman.containerPort
  const builderInstall = resolveInstallCommand(drsPlan, false)
  const runtimeInstall = resolveInstallCommand(drsPlan, true)
  const cmd = service.podman.command?.length
    ? JSON.stringify(service.podman.command)
    : '["node", "dist/index.js"]'

  return [
    GENERATED_HEADER,
    '',
    `FROM ${nodeImage} AS builder`,
    '',
    aptInstallLines(backend.systemPackages),
    'WORKDIR /app',
    '',
    'COPY package.json package-lock.json ./',
    'COPY generated_modules ./generated_modules',
    `RUN ${builderInstall}`,
    '',
    'COPY tsconfig.json ./',
    'COPY prisma ./prisma',
    'COPY scripts ./scripts',
    'COPY src ./src',
    '',
    `RUN ${backend.buildCommand}`,
    '',
    `FROM ${nodeImage} AS runtime`,
    '',
    aptInstallLines(backend.systemPackages),
    'WORKDIR /app',
    '',
    'COPY package.json package-lock.json ./',
    'COPY generated_modules ./generated_modules',
    `RUN ${runtimeInstall}`,
    '',
    'COPY --from=builder /app/dist ./dist',
    'COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma',
    'COPY --from=builder /app/node_modules/@prisma/client ./node_modules/@prisma/client',
    '',
    `EXPOSE ${exposePort}`,
    '',
    `CMD ${cmd}`,
    '',
  ].join('\n')
}

export function getBackendDockerfileRelativePath(docker: {
  readonly backend: NormalizedMeshCiDockerBackendConfig
}): string {
  return docker.backend.dockerfile
}
